### ISSUE TITLE
//kythe/docs/schema:schema build broken

### ISSUE THREAD

**Issue by salguarnieri** [google/kythe#2967]
bazel build //kythe/docs/schema returns errors like:

```
kythe/java/com/google/devtools/kythe/analyzers/java/indexer: Cannot locate runfiles directory. (Set $JAVA_RUNFILES to inhibit searching.)
[ FAILED INDEX: Classes can be annotated. ]
```

**Comment by schroederc** [comment]
There's a weird non-hermeticity.  If you run `bazel test //...` before `bazel build //kythe/docs/schema`, the runfiles directory is setup correctly and the schema doc can build.  This probably because we only specify the indexer as a data dependency instead of a tool dependency.

However, I'm finding that #2970 independently broke the schema build with the following error:

```
kythe/docs/schema/example-java.sh: line 37: shasum: command not found
```

**Comment by salguarnieri** [comment]
Well, that broke on osx because of:

```
perl version 5.18.2 can't run /private/var/tmp/_bazel_salguarnieri/ca16ea5a435d8ac2288f379cdf092007/external/local_config_tools/shasum.  Try the alternative(s):

(Error: no alternatives found)

Run "man perl" for more information about multiple version support in
Mac OS X.
```
